#!/bin/sh

printf "Initializing postgresql service...\n"
until pg_isready -h "db"
do
    printf "Postgres is not ready to accept connections, waiting.....\n"
    sleep 1
done
python manage.py migrate

printf "Creating superuser if not already exists...\n"
python manage.py shell << EOL
from django.contrib.auth import get_user_model
User = get_user_model()
try:
    User.objects.get(username='root')
    print('Superuser already exists, not created')
except User.DoesNotExist:
    print('Superuser not found, creating...')
    User.objects.create_superuser(username='root', password='rootroot',
                                  email='root@bugtracker.com')
    print('Superuser created')
EOL
printf "Copying static files..."
python manage.py collectstatic --no-input

python manage.py runserver 0.0.0.0:8000
