name: Build pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t educomtoppers/bugtracker-web ./web
        docker build -t educomtoppers/bugtracker-vue ./vue

    - name: Lint Code
      run: docker-compose run web pycodestyle

    - name: Publish image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push educomtoppers/bugtracker-web 
        docker push educomtoppers/bugtracker-vue
